name: release
on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version Type: (Release, Beta, Alpha)'
        required: true
        default: 'release'

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog-file: CHANGELOG.md
          version-type: ${{ github.event.inputs.versionType }}

          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
